# Generated by Django 4.0 on 2021-12-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Расстояние')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
    ]
